<?php

namespace Database\Seeders;

use App\Models\Customer;
use App\Models\CustomerLevel;
use App\Models\Store;
use Illuminate\Database\Seeder;

/**
 * 會員資料 Seeder
 */
class CustomerSeeder extends Seeder
{
    public function run(): void
    {
        $levels = CustomerLevel::all()->keyBy('level_code');
        $stores = Store::where('status', 'ACTIVE')->get();

        $customers = [
            // 鑽石會員 (level_code = 5)
            [
                'member_no' => 'M2024000001',
                'name' => '張志明',
                'gender' => 'M',
                'birthday' => '1985-03-15',
                'phone' => '0912-345-678',
                'email' => 'zhiming.zhang@example.com',
                'address' => '台北市大安區敦化南路一段100號',
                'level_id' => $levels[5]->id,
                'total_spending' => 350000.00,
                'total_points' => 35000,
                'available_points' => 12500,
                'join_date' => '2022-01-15',
                'join_store_id' => $stores[0]->id,
                'status' => 'ACTIVE',
            ],
            // 白金會員
            [
                'member_no' => 'M2024000002',
                'name' => '林美玲',
                'gender' => 'F',
                'birthday' => '1990-07-22',
                'phone' => '0923-456-789',
                'email' => 'meiling.lin@example.com',
                'address' => '台北市信義區松仁路50號',
                'level_id' => $levels[4]->id,
                'total_spending' => 150000.00,
                'total_points' => 15000,
                'available_points' => 8200,
                'join_date' => '2022-06-20',
                'join_store_id' => $stores[0]->id,
                'status' => 'ACTIVE',
            ],
            [
                'member_no' => 'M2024000003',
                'name' => '王大偉',
                'gender' => 'M',
                'birthday' => '1978-11-08',
                'phone' => '0934-567-890',
                'email' => 'dawei.wang@example.com',
                'address' => '新北市板橋區文化路二段88號',
                'level_id' => $levels[4]->id,
                'total_spending' => 120000.00,
                'total_points' => 12000,
                'available_points' => 5600,
                'join_date' => '2022-09-10',
                'join_store_id' => $stores[1]->id,
                'status' => 'ACTIVE',
            ],
            // 金卡會員
            [
                'member_no' => 'M2024000004',
                'name' => '陳怡君',
                'gender' => 'F',
                'birthday' => '1995-02-28',
                'phone' => '0945-678-901',
                'email' => 'yijun.chen@example.com',
                'address' => '台中市西屯區台灣大道三段200號',
                'level_id' => $levels[3]->id,
                'total_spending' => 55000.00,
                'total_points' => 5500,
                'available_points' => 3200,
                'join_date' => '2023-01-05',
                'join_store_id' => $stores[2]->id,
                'status' => 'ACTIVE',
            ],
            [
                'member_no' => 'M2024000005',
                'name' => '黃建文',
                'gender' => 'M',
                'birthday' => '1988-09-12',
                'phone' => '0956-789-012',
                'email' => 'jianwen.huang@example.com',
                'address' => '高雄市前鎮區中華五路500號',
                'level_id' => $levels[3]->id,
                'total_spending' => 42000.00,
                'total_points' => 4200,
                'available_points' => 1800,
                'join_date' => '2023-03-18',
                'join_store_id' => $stores[3]->id,
                'status' => 'ACTIVE',
            ],
            [
                'member_no' => 'M2024000006',
                'name' => '吳佳蓉',
                'gender' => 'F',
                'birthday' => '1992-05-20',
                'phone' => '0967-890-123',
                'email' => 'jiarong.wu@example.com',
                'address' => '台北市中山區南京東路三段150號',
                'level_id' => $levels[3]->id,
                'total_spending' => 38000.00,
                'total_points' => 3800,
                'available_points' => 2100,
                'join_date' => '2023-05-22',
                'join_store_id' => $stores[0]->id,
                'status' => 'ACTIVE',
            ],
            // 銀卡會員
            [
                'member_no' => 'M2024000007',
                'name' => '李宗翰',
                'gender' => 'M',
                'birthday' => '1983-12-05',
                'phone' => '0978-901-234',
                'email' => 'zonghan.li@example.com',
                'address' => '新北市中和區中正路300號',
                'level_id' => $levels[2]->id,
                'total_spending' => 18000.00,
                'total_points' => 1800,
                'available_points' => 900,
                'join_date' => '2023-07-10',
                'join_store_id' => $stores[1]->id,
                'status' => 'ACTIVE',
            ],
            [
                'member_no' => 'M2024000008',
                'name' => '許雅婷',
                'gender' => 'F',
                'birthday' => '1998-08-18',
                'phone' => '0989-012-345',
                'email' => 'yating.xu@example.com',
                'address' => '台中市北區三民路二段60號',
                'level_id' => $levels[2]->id,
                'total_spending' => 15000.00,
                'total_points' => 1500,
                'available_points' => 750,
                'join_date' => '2023-08-25',
                'join_store_id' => $stores[2]->id,
                'status' => 'ACTIVE',
            ],
            [
                'member_no' => 'M2024000009',
                'name' => '周俊傑',
                'gender' => 'M',
                'birthday' => '1991-04-03',
                'phone' => '0910-123-456',
                'email' => 'junjie.zhou@example.com',
                'address' => '高雄市鼓山區美術館路80號',
                'level_id' => $levels[2]->id,
                'total_spending' => 12000.00,
                'total_points' => 1200,
                'available_points' => 600,
                'join_date' => '2023-10-12',
                'join_store_id' => $stores[3]->id,
                'status' => 'ACTIVE',
            ],
            [
                'member_no' => 'M2024000010',
                'name' => '楊淑芬',
                'gender' => 'F',
                'birthday' => '1987-06-30',
                'phone' => '0921-234-567',
                'email' => 'shufen.yang@example.com',
                'address' => '桃園市中壢區中央西路二段120號',
                'level_id' => $levels[2]->id,
                'total_spending' => 11000.00,
                'total_points' => 1100,
                'available_points' => 550,
                'join_date' => '2023-11-08',
                'join_store_id' => $stores[0]->id,
                'status' => 'ACTIVE',
            ],
            // 一般會員
            [
                'member_no' => 'M2024000011',
                'name' => '劉家豪',
                'gender' => 'M',
                'birthday' => '2000-01-25',
                'phone' => '0932-345-678',
                'email' => 'jiahao.liu@example.com',
                'address' => '台北市萬華區西園路一段200號',
                'level_id' => $levels[1]->id,
                'total_spending' => 5000.00,
                'total_points' => 500,
                'available_points' => 300,
                'join_date' => '2024-01-15',
                'join_store_id' => $stores[1]->id,
                'status' => 'ACTIVE',
            ],
            [
                'member_no' => 'M2024000012',
                'name' => '蔡依琳',
                'gender' => 'F',
                'birthday' => '1996-10-10',
                'phone' => '0943-456-789',
                'email' => 'yilin.cai@example.com',
                'address' => '新北市新莊區中正路400號',
                'level_id' => $levels[1]->id,
                'total_spending' => 3500.00,
                'total_points' => 350,
                'available_points' => 200,
                'join_date' => '2024-02-20',
                'join_store_id' => $stores[0]->id,
                'status' => 'ACTIVE',
            ],
            [
                'member_no' => 'M2024000013',
                'name' => '鄭文彥',
                'gender' => 'M',
                'birthday' => '1993-07-07',
                'phone' => '0954-567-890',
                'email' => 'wenyan.zheng@example.com',
                'address' => '台中市南屯區公益路二段300號',
                'level_id' => $levels[1]->id,
                'total_spending' => 2800.00,
                'total_points' => 280,
                'available_points' => 150,
                'join_date' => '2024-03-05',
                'join_store_id' => $stores[2]->id,
                'status' => 'ACTIVE',
            ],
            [
                'member_no' => 'M2024000014',
                'name' => '謝佩珊',
                'gender' => 'F',
                'birthday' => '1989-03-22',
                'phone' => '0965-678-901',
                'email' => 'peishan.xie@example.com',
                'address' => '高雄市左營區博愛二路500號',
                'level_id' => $levels[1]->id,
                'total_spending' => 2200.00,
                'total_points' => 220,
                'available_points' => 100,
                'join_date' => '2024-04-10',
                'join_store_id' => $stores[3]->id,
                'status' => 'ACTIVE',
            ],
            [
                'member_no' => 'M2024000015',
                'name' => '蘇志偉',
                'gender' => 'M',
                'birthday' => '1982-11-15',
                'phone' => '0976-789-012',
                'email' => 'zhiwei.su@example.com',
                'address' => '新北市三重區重新路三段150號',
                'level_id' => $levels[1]->id,
                'total_spending' => 1500.00,
                'total_points' => 150,
                'available_points' => 80,
                'join_date' => '2024-05-18',
                'join_store_id' => $stores[1]->id,
                'status' => 'ACTIVE',
            ],
            [
                'member_no' => 'M2024000016',
                'name' => '葉曉婷',
                'gender' => 'F',
                'birthday' => '1997-09-02',
                'phone' => '0987-890-123',
                'email' => 'xiaoting.ye@example.com',
                'address' => '台北市內湖區內湖路一段250號',
                'level_id' => $levels[1]->id,
                'total_spending' => 1200.00,
                'total_points' => 120,
                'available_points' => 60,
                'join_date' => '2024-06-22',
                'join_store_id' => $stores[0]->id,
                'status' => 'ACTIVE',
            ],
            [
                'member_no' => 'M2024000017',
                'name' => '曾國華',
                'gender' => 'M',
                'birthday' => '1986-05-28',
                'phone' => '0918-901-234',
                'email' => 'guohua.zeng@example.com',
                'address' => '桃園市桃園區中山路600號',
                'level_id' => $levels[1]->id,
                'total_spending' => 800.00,
                'total_points' => 80,
                'available_points' => 40,
                'join_date' => '2024-07-30',
                'join_store_id' => $stores[2]->id,
                'status' => 'ACTIVE',
            ],
            [
                'member_no' => 'M2024000018',
                'name' => '沈雅文',
                'gender' => 'F',
                'birthday' => '1994-12-12',
                'phone' => '0929-012-345',
                'email' => 'yawen.shen@example.com',
                'address' => '台中市西區美村路一段100號',
                'level_id' => $levels[1]->id,
                'total_spending' => 500.00,
                'total_points' => 50,
                'available_points' => 25,
                'join_date' => '2024-08-15',
                'join_store_id' => $stores[2]->id,
                'status' => 'ACTIVE',
            ],
            // 停權會員
            [
                'member_no' => 'M2024000019',
                'name' => '呂明峰',
                'gender' => 'M',
                'birthday' => '1980-04-17',
                'phone' => '0930-123-456',
                'email' => 'mingfeng.lv@example.com',
                'address' => '台北市松山區民生東路五段180號',
                'level_id' => $levels[2]->id,
                'total_spending' => 15000.00,
                'total_points' => 1500,
                'available_points' => 0,
                'join_date' => '2023-02-10',
                'join_store_id' => $stores[0]->id,
                'notes' => '因退貨異常暫停會員資格',
                'status' => 'INACTIVE',
            ],
            [
                'member_no' => 'M2024000020',
                'name' => '賴淑華',
                'gender' => 'F',
                'birthday' => '1975-08-05',
                'phone' => '0941-234-567',
                'email' => 'shuhua.lai@example.com',
                'address' => '高雄市三民區建工路200號',
                'level_id' => $levels[1]->id,
                'total_spending' => 3000.00,
                'total_points' => 300,
                'available_points' => 0,
                'join_date' => '2024-01-20',
                'join_store_id' => $stores[3]->id,
                'notes' => '會員申請暫停',
                'status' => 'INACTIVE',
            ],
        ];

        foreach ($customers as $customer) {
            Customer::create($customer);
        }
    }
}
