<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\Supplier;
use Illuminate\Database\Seeder;

/**
 * 商品資料 Seeder
 */
class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // 取得分類
        $categories = Category::all()->keyBy('code');
        // 取得供應商
        $suppliers = Supplier::where('status', 'ACTIVE')->get()->keyBy('code');

        $products = [
            // ==================== 3C電子 - 手機通訊 ====================
            [
                'sku' => 'PHONE-001',
                'barcode' => '4710000000001',
                'name' => 'iPhone 15 Pro 256GB 鈦金屬原色',
                'short_name' => 'iPhone 15 Pro',
                'category_id' => $categories['CAT-IPHONE']->id,
                'brand' => 'Apple',
                'description' => 'Apple iPhone 15 Pro，搭載 A17 Pro 晶片，鈦金屬設計，256GB 儲存空間',
                'unit' => 'PCS',
                'cost_price' => 32000.00,
                'selling_price' => 36900.00,
                'member_price' => 35900.00,
                'min_price' => 34000.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 10,
                'max_stock' => 50,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP001']->id,
                'status' => 'ACTIVE',
            ],
            [
                'sku' => 'PHONE-002',
                'barcode' => '4710000000002',
                'name' => 'Samsung Galaxy S24 Ultra 512GB 鈦黑',
                'short_name' => 'Galaxy S24 Ultra',
                'category_id' => $categories['CAT-ANDROID']->id,
                'brand' => 'Samsung',
                'description' => 'Samsung Galaxy S24 Ultra，搭載 Snapdragon 8 Gen 3 處理器，2億畫素相機',
                'unit' => 'PCS',
                'cost_price' => 35000.00,
                'selling_price' => 41900.00,
                'member_price' => 40900.00,
                'min_price' => 38000.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 8,
                'max_stock' => 40,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP001']->id,
                'status' => 'ACTIVE',
            ],
            [
                'sku' => 'PHONE-003',
                'barcode' => '4710000000003',
                'name' => 'ASUS Zenfone 11 Ultra 256GB',
                'short_name' => 'Zenfone 11 Ultra',
                'category_id' => $categories['CAT-ANDROID']->id,
                'brand' => 'ASUS',
                'description' => 'ASUS Zenfone 11 Ultra 旗艦手機，AI 拍照功能',
                'unit' => 'PCS',
                'cost_price' => 22000.00,
                'selling_price' => 25990.00,
                'member_price' => 24990.00,
                'min_price' => 23000.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 10,
                'max_stock' => 50,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP001']->id,
                'status' => 'ACTIVE',
            ],
            [
                'sku' => 'ACC-001',
                'barcode' => '4710000000004',
                'name' => 'Apple 原廠 MagSafe 充電器',
                'short_name' => 'MagSafe充電器',
                'category_id' => $categories['CAT-ACC']->id,
                'brand' => 'Apple',
                'description' => 'Apple MagSafe 無線充電器，15W 快充',
                'unit' => 'PCS',
                'cost_price' => 800.00,
                'selling_price' => 1190.00,
                'member_price' => 1090.00,
                'min_price' => 900.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 30,
                'max_stock' => 200,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP001']->id,
                'status' => 'ACTIVE',
            ],
            [
                'sku' => 'ACC-002',
                'barcode' => '4710000000005',
                'name' => '犀牛盾 iPhone 15 Pro 防摔殼',
                'short_name' => '犀牛盾防摔殼',
                'category_id' => $categories['CAT-ACC']->id,
                'brand' => 'RhinoShield',
                'description' => '犀牛盾 SolidSuit 防摔殼，軍規防摔認證',
                'unit' => 'PCS',
                'cost_price' => 650.00,
                'selling_price' => 990.00,
                'member_price' => 890.00,
                'min_price' => 750.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 50,
                'max_stock' => 300,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP001']->id,
                'status' => 'ACTIVE',
            ],

            // ==================== 3C電子 - 電腦週邊 ====================
            [
                'sku' => 'COMP-001',
                'barcode' => '4710000000006',
                'name' => 'Logitech MX Master 3S 無線滑鼠',
                'short_name' => 'MX Master 3S',
                'category_id' => $categories['CAT-COMP']->id,
                'brand' => 'Logitech',
                'description' => '羅技 MX Master 3S 高階無線滑鼠，靜音點擊，8000 DPI',
                'unit' => 'PCS',
                'cost_price' => 2500.00,
                'selling_price' => 3490.00,
                'member_price' => 3290.00,
                'min_price' => 2800.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 15,
                'max_stock' => 100,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP002']->id,
                'status' => 'ACTIVE',
            ],
            [
                'sku' => 'COMP-002',
                'barcode' => '4710000000007',
                'name' => 'ASUS ROG Strix 27吋電競螢幕',
                'short_name' => 'ROG 27吋螢幕',
                'category_id' => $categories['CAT-COMP']->id,
                'brand' => 'ASUS',
                'description' => 'ASUS ROG Strix XG27AQ 電競螢幕，170Hz，1ms反應',
                'unit' => 'PCS',
                'cost_price' => 11000.00,
                'selling_price' => 13990.00,
                'member_price' => 12990.00,
                'min_price' => 12000.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 5,
                'max_stock' => 30,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP002']->id,
                'status' => 'ACTIVE',
            ],
            [
                'sku' => 'COMP-003',
                'barcode' => '4710000000008',
                'name' => '機械式鍵盤 Cherry MX 茶軸',
                'short_name' => 'Cherry茶軸鍵盤',
                'category_id' => $categories['CAT-COMP']->id,
                'brand' => 'Ducky',
                'description' => 'Ducky One 3 機械式鍵盤，Cherry MX 茶軸，熱插拔',
                'unit' => 'PCS',
                'cost_price' => 2800.00,
                'selling_price' => 3890.00,
                'member_price' => 3690.00,
                'min_price' => 3200.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 10,
                'max_stock' => 60,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP002']->id,
                'status' => 'ACTIVE',
            ],

            // ==================== 3C電子 - 耳機音響 ====================
            [
                'sku' => 'AUDIO-001',
                'barcode' => '4710000000009',
                'name' => 'Sony WH-1000XM5 降噪耳機',
                'short_name' => 'Sony XM5',
                'category_id' => $categories['CAT-AUDIO']->id,
                'brand' => 'Sony',
                'description' => 'Sony WH-1000XM5 無線藍牙降噪耳罩式耳機，30小時續航',
                'unit' => 'PCS',
                'cost_price' => 8500.00,
                'selling_price' => 10900.00,
                'member_price' => 10400.00,
                'min_price' => 9500.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 10,
                'max_stock' => 50,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP001']->id,
                'status' => 'ACTIVE',
            ],
            [
                'sku' => 'AUDIO-002',
                'barcode' => '4710000000010',
                'name' => 'AirPods Pro 2 USB-C',
                'short_name' => 'AirPods Pro 2',
                'category_id' => $categories['CAT-AUDIO']->id,
                'brand' => 'Apple',
                'description' => 'Apple AirPods Pro 第二代，USB-C 充電盒，主動式降噪',
                'unit' => 'PCS',
                'cost_price' => 5800.00,
                'selling_price' => 7490.00,
                'member_price' => 7190.00,
                'min_price' => 6500.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 20,
                'max_stock' => 100,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP001']->id,
                'status' => 'ACTIVE',
            ],

            // ==================== 服飾配件 - 男裝 ====================
            [
                'sku' => 'MEN-001',
                'barcode' => '4710000000011',
                'name' => '男士商務休閒西裝外套',
                'short_name' => '商務西裝外套',
                'category_id' => $categories['CAT-MEN']->id,
                'brand' => 'GQ',
                'description' => '高質感商務休閒西裝外套，修身版型',
                'unit' => 'PCS',
                'cost_price' => 1500.00,
                'selling_price' => 2990.00,
                'member_price' => 2690.00,
                'min_price' => 2200.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 10,
                'max_stock' => 50,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP006']->id,
                'status' => 'ACTIVE',
            ],
            [
                'sku' => 'MEN-002',
                'barcode' => '4710000000012',
                'name' => '純棉素色圓領T恤',
                'short_name' => '素色T恤',
                'category_id' => $categories['CAT-MEN']->id,
                'brand' => 'UNIQLO',
                'description' => '100%純棉素色T恤，舒適透氣',
                'unit' => 'PCS',
                'cost_price' => 150.00,
                'selling_price' => 390.00,
                'member_price' => 350.00,
                'min_price' => 290.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 50,
                'max_stock' => 300,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP006']->id,
                'status' => 'ACTIVE',
            ],

            // ==================== 服飾配件 - 女裝 ====================
            [
                'sku' => 'WOMEN-001',
                'barcode' => '4710000000013',
                'name' => '韓版修身連身洋裝',
                'short_name' => '修身洋裝',
                'category_id' => $categories['CAT-WOMEN']->id,
                'brand' => 'MOMA',
                'description' => '韓版設計修身連身洋裝，優雅氣質',
                'unit' => 'PCS',
                'cost_price' => 800.00,
                'selling_price' => 1690.00,
                'member_price' => 1490.00,
                'min_price' => 1200.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 15,
                'max_stock' => 80,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP006']->id,
                'status' => 'ACTIVE',
            ],
            [
                'sku' => 'WOMEN-002',
                'barcode' => '4710000000014',
                'name' => '雪紡碎花上衣',
                'short_name' => '碎花上衣',
                'category_id' => $categories['CAT-WOMEN']->id,
                'brand' => 'MOMA',
                'description' => '輕盈雪紡碎花上衣，春夏必備',
                'unit' => 'PCS',
                'cost_price' => 400.00,
                'selling_price' => 890.00,
                'member_price' => 790.00,
                'min_price' => 650.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 20,
                'max_stock' => 100,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP006']->id,
                'status' => 'ACTIVE',
            ],

            // ==================== 服飾配件 - 鞋類 ====================
            [
                'sku' => 'SHOES-001',
                'barcode' => '4710000000015',
                'name' => 'Nike Air Force 1 白色',
                'short_name' => 'AF1 白',
                'category_id' => $categories['CAT-SHOES']->id,
                'brand' => 'Nike',
                'description' => 'Nike Air Force 1 經典白色休閒鞋',
                'unit' => 'PAIR',
                'cost_price' => 2200.00,
                'selling_price' => 3200.00,
                'member_price' => 2990.00,
                'min_price' => 2600.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 15,
                'max_stock' => 80,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP006']->id,
                'status' => 'ACTIVE',
            ],
            [
                'sku' => 'SHOES-002',
                'barcode' => '4710000000016',
                'name' => 'Adidas Ultraboost 慢跑鞋',
                'short_name' => 'Ultraboost',
                'category_id' => $categories['CAT-SHOES']->id,
                'brand' => 'Adidas',
                'description' => 'Adidas Ultraboost 專業慢跑鞋，Boost 中底科技',
                'unit' => 'PAIR',
                'cost_price' => 3500.00,
                'selling_price' => 5200.00,
                'member_price' => 4800.00,
                'min_price' => 4200.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 10,
                'max_stock' => 60,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP006']->id,
                'status' => 'ACTIVE',
            ],

            // ==================== 服飾配件 - 包包配件 ====================
            [
                'sku' => 'BAG-001',
                'barcode' => '4710000000017',
                'name' => '真皮商務公事包',
                'short_name' => '真皮公事包',
                'category_id' => $categories['CAT-BAGS']->id,
                'brand' => 'Samsonite',
                'description' => '真皮商務公事包，可放15吋筆電',
                'unit' => 'PCS',
                'cost_price' => 3000.00,
                'selling_price' => 4990.00,
                'member_price' => 4590.00,
                'min_price' => 4000.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 8,
                'max_stock' => 40,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP006']->id,
                'status' => 'ACTIVE',
            ],

            // ==================== 食品飲料 - 零食餅乾 ====================
            [
                'sku' => 'SNACK-001',
                'barcode' => '4710000000018',
                'name' => '義美小泡芙 巧克力口味',
                'short_name' => '小泡芙巧克力',
                'category_id' => $categories['CAT-SNACK']->id,
                'brand' => '義美',
                'description' => '義美小泡芙巧克力口味，65g',
                'unit' => 'PKG',
                'cost_price' => 20.00,
                'selling_price' => 35.00,
                'member_price' => 32.00,
                'min_price' => 28.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 100,
                'max_stock' => 500,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP003']->id,
                'status' => 'ACTIVE',
            ],
            [
                'sku' => 'SNACK-002',
                'barcode' => '4710000000019',
                'name' => '樂事洋芋片 原味',
                'short_name' => '樂事原味',
                'category_id' => $categories['CAT-SNACK']->id,
                'brand' => 'Lay\'s',
                'description' => '樂事洋芋片原味，97g',
                'unit' => 'PKG',
                'cost_price' => 25.00,
                'selling_price' => 45.00,
                'member_price' => 42.00,
                'min_price' => 35.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 100,
                'max_stock' => 500,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP003']->id,
                'status' => 'ACTIVE',
            ],
            [
                'sku' => 'SNACK-003',
                'barcode' => '4710000000020',
                'name' => '旺旺仙貝 家庭號',
                'short_name' => '旺旺仙貝',
                'category_id' => $categories['CAT-SNACK']->id,
                'brand' => '旺旺',
                'description' => '旺旺仙貝家庭號，350g',
                'unit' => 'PKG',
                'cost_price' => 60.00,
                'selling_price' => 99.00,
                'member_price' => 89.00,
                'min_price' => 79.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 80,
                'max_stock' => 400,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP003']->id,
                'status' => 'ACTIVE',
            ],

            // ==================== 食品飲料 - 飲料沖泡 ====================
            [
                'sku' => 'DRINK-001',
                'barcode' => '4710000000021',
                'name' => '可口可樂 600ml',
                'short_name' => '可口可樂',
                'category_id' => $categories['CAT-DRINK']->id,
                'brand' => 'Coca-Cola',
                'description' => '可口可樂 600ml 寶特瓶',
                'unit' => 'BTL',
                'cost_price' => 18.00,
                'selling_price' => 29.00,
                'member_price' => 27.00,
                'min_price' => 22.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 200,
                'max_stock' => 1000,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP003']->id,
                'status' => 'ACTIVE',
            ],
            [
                'sku' => 'DRINK-002',
                'barcode' => '4710000000022',
                'name' => '統一純喫茶 無糖綠茶',
                'short_name' => '純喫茶綠茶',
                'category_id' => $categories['CAT-DRINK']->id,
                'brand' => '統一',
                'description' => '統一純喫茶無糖綠茶，650ml',
                'unit' => 'BTL',
                'cost_price' => 15.00,
                'selling_price' => 25.00,
                'member_price' => 23.00,
                'min_price' => 20.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 200,
                'max_stock' => 1000,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP003']->id,
                'status' => 'ACTIVE',
            ],
            [
                'sku' => 'DRINK-003',
                'barcode' => '4710000000023',
                'name' => 'UCC 職人咖啡 無糖',
                'short_name' => 'UCC職人咖啡',
                'category_id' => $categories['CAT-DRINK']->id,
                'brand' => 'UCC',
                'description' => 'UCC 職人咖啡無糖，900ml',
                'unit' => 'BTL',
                'cost_price' => 35.00,
                'selling_price' => 59.00,
                'member_price' => 55.00,
                'min_price' => 49.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 100,
                'max_stock' => 500,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP003']->id,
                'status' => 'ACTIVE',
            ],

            // ==================== 居家生活 - 傢俱寢具 ====================
            [
                'sku' => 'FURN-001',
                'barcode' => '4710000000024',
                'name' => '乳膠記憶枕 護頸款',
                'short_name' => '記憶枕護頸',
                'category_id' => $categories['CAT-FURN']->id,
                'brand' => '3M',
                'description' => '3M 乳膠記憶枕護頸款，人體工學設計',
                'unit' => 'PCS',
                'cost_price' => 800.00,
                'selling_price' => 1490.00,
                'member_price' => 1390.00,
                'min_price' => 1100.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 20,
                'max_stock' => 100,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP005']->id,
                'status' => 'ACTIVE',
            ],
            [
                'sku' => 'FURN-002',
                'barcode' => '4710000000025',
                'name' => '天絲床包組 雙人',
                'short_name' => '天絲床包雙人',
                'category_id' => $categories['CAT-FURN']->id,
                'brand' => 'HOLA',
                'description' => '100%天絲床包組雙人尺寸，含床包+枕套x2',
                'unit' => 'SET',
                'cost_price' => 1500.00,
                'selling_price' => 2990.00,
                'member_price' => 2690.00,
                'min_price' => 2200.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 10,
                'max_stock' => 50,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP005']->id,
                'status' => 'ACTIVE',
            ],

            // ==================== 居家生活 - 廚房用品 ====================
            [
                'sku' => 'KITCH-001',
                'barcode' => '4710000000026',
                'name' => '不鏽鋼保溫瓶 500ml',
                'short_name' => '保溫瓶500ml',
                'category_id' => $categories['CAT-KITCH']->id,
                'brand' => '象印',
                'description' => '象印不鏽鋼真空保溫瓶，500ml，保溫保冷',
                'unit' => 'PCS',
                'cost_price' => 500.00,
                'selling_price' => 890.00,
                'member_price' => 790.00,
                'min_price' => 650.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 30,
                'max_stock' => 150,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP005']->id,
                'status' => 'ACTIVE',
            ],
            [
                'sku' => 'KITCH-002',
                'barcode' => '4710000000027',
                'name' => '玻璃保鮮盒三件組',
                'short_name' => '玻璃保鮮盒組',
                'category_id' => $categories['CAT-KITCH']->id,
                'brand' => 'Glasslock',
                'description' => 'Glasslock 強化玻璃保鮮盒三件組，微波爐適用',
                'unit' => 'SET',
                'cost_price' => 400.00,
                'selling_price' => 699.00,
                'member_price' => 649.00,
                'min_price' => 550.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 25,
                'max_stock' => 120,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP005']->id,
                'status' => 'ACTIVE',
            ],

            // ==================== 居家生活 - 清潔用品 ====================
            [
                'sku' => 'CLEAN-001',
                'barcode' => '4710000000028',
                'name' => '花王魔術靈 浴室清潔劑',
                'short_name' => '魔術靈浴室',
                'category_id' => $categories['CAT-CLEAN']->id,
                'brand' => '花王',
                'description' => '花王魔術靈浴室清潔劑，500ml 噴霧瓶',
                'unit' => 'BTL',
                'cost_price' => 65.00,
                'selling_price' => 109.00,
                'member_price' => 99.00,
                'min_price' => 85.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 50,
                'max_stock' => 300,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP003']->id,
                'status' => 'ACTIVE',
            ],
            [
                'sku' => 'CLEAN-002',
                'barcode' => '4710000000029',
                'name' => '白蘭洗衣精 柔軟護纖',
                'short_name' => '白蘭洗衣精',
                'category_id' => $categories['CAT-CLEAN']->id,
                'brand' => '白蘭',
                'description' => '白蘭洗衣精柔軟護纖，2.5kg',
                'unit' => 'BTL',
                'cost_price' => 120.00,
                'selling_price' => 199.00,
                'member_price' => 179.00,
                'min_price' => 159.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 40,
                'max_stock' => 200,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP003']->id,
                'status' => 'ACTIVE',
            ],

            // ==================== 美妝保養 - 保養品 ====================
            [
                'sku' => 'SKIN-001',
                'barcode' => '4710000000030',
                'name' => '蘭蔻小黑瓶精華液 50ml',
                'short_name' => '小黑瓶50ml',
                'category_id' => $categories['CAT-SKIN']->id,
                'brand' => 'Lancôme',
                'description' => '蘭蔻小黑瓶超進化肌因賦活露，50ml',
                'unit' => 'BTL',
                'cost_price' => 2500.00,
                'selling_price' => 3800.00,
                'member_price' => 3500.00,
                'min_price' => 3200.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 10,
                'max_stock' => 50,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP004']->id,
                'status' => 'ACTIVE',
            ],
            [
                'sku' => 'SKIN-002',
                'barcode' => '4710000000031',
                'name' => 'SK-II 青春露 230ml',
                'short_name' => 'SK-II青春露',
                'category_id' => $categories['CAT-SKIN']->id,
                'brand' => 'SK-II',
                'description' => 'SK-II 青春露神仙水，230ml',
                'unit' => 'BTL',
                'cost_price' => 4000.00,
                'selling_price' => 5980.00,
                'member_price' => 5580.00,
                'min_price' => 5200.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 8,
                'max_stock' => 40,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP004']->id,
                'status' => 'ACTIVE',
            ],
            [
                'sku' => 'SKIN-003',
                'barcode' => '4710000000032',
                'name' => '理膚寶水多容安舒緩化妝水',
                'short_name' => '理膚舒緩化妝水',
                'category_id' => $categories['CAT-SKIN']->id,
                'brand' => 'La Roche-Posay',
                'description' => '理膚寶水多容安舒緩保濕化妝水，200ml',
                'unit' => 'BTL',
                'cost_price' => 450.00,
                'selling_price' => 750.00,
                'member_price' => 690.00,
                'min_price' => 600.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 20,
                'max_stock' => 100,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP004']->id,
                'status' => 'ACTIVE',
            ],

            // ==================== 美妝保養 - 彩妝 ====================
            [
                'sku' => 'MAKEUP-001',
                'barcode' => '4710000000033',
                'name' => 'MAC 子彈唇膏 Ruby Woo',
                'short_name' => 'MAC唇膏Ruby',
                'category_id' => $categories['CAT-MAKEUP']->id,
                'brand' => 'MAC',
                'description' => 'MAC 時尚子彈唇膏 Ruby Woo 正紅色',
                'unit' => 'PCS',
                'cost_price' => 500.00,
                'selling_price' => 850.00,
                'member_price' => 790.00,
                'min_price' => 700.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 20,
                'max_stock' => 100,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP004']->id,
                'status' => 'ACTIVE',
            ],
            [
                'sku' => 'MAKEUP-002',
                'barcode' => '4710000000034',
                'name' => 'Maybelline 超持久眼線液',
                'short_name' => '媚比琳眼線液',
                'category_id' => $categories['CAT-MAKEUP']->id,
                'brand' => 'Maybelline',
                'description' => 'Maybelline 超持久流線姬眼線液，極細黑',
                'unit' => 'PCS',
                'cost_price' => 180.00,
                'selling_price' => 320.00,
                'member_price' => 290.00,
                'min_price' => 250.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 30,
                'max_stock' => 150,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP004']->id,
                'status' => 'ACTIVE',
            ],

            // ==================== 美妝保養 - 髮品護理 ====================
            [
                'sku' => 'HAIR-001',
                'barcode' => '4710000000035',
                'name' => '摩洛哥優油護髮油 100ml',
                'short_name' => '摩洛哥護髮油',
                'category_id' => $categories['CAT-HAIR']->id,
                'brand' => 'Moroccanoil',
                'description' => 'Moroccanoil 摩洛哥優油護髮精華油，100ml',
                'unit' => 'BTL',
                'cost_price' => 800.00,
                'selling_price' => 1380.00,
                'member_price' => 1280.00,
                'min_price' => 1100.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 15,
                'max_stock' => 80,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP004']->id,
                'status' => 'ACTIVE',
            ],
            [
                'sku' => 'HAIR-002',
                'barcode' => '4710000000036',
                'name' => '潘婷乳液修護洗髮乳 700ml',
                'short_name' => '潘婷洗髮乳',
                'category_id' => $categories['CAT-HAIR']->id,
                'brand' => 'Pantene',
                'description' => '潘婷乳液修護洗髮乳，700ml',
                'unit' => 'BTL',
                'cost_price' => 120.00,
                'selling_price' => 219.00,
                'member_price' => 199.00,
                'min_price' => 169.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 40,
                'max_stock' => 200,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP004']->id,
                'status' => 'ACTIVE',
            ],

            // ==================== 下架商品 ====================
            [
                'sku' => 'OLD-001',
                'barcode' => '4710000000099',
                'name' => '舊款商品（已停售）',
                'short_name' => '舊款商品',
                'category_id' => $categories['CAT-ELEC']->id,
                'brand' => 'NoName',
                'description' => '此商品已停售',
                'unit' => 'PCS',
                'cost_price' => 100.00,
                'selling_price' => 199.00,
                'tax_type' => 'TAXABLE',
                'safety_stock' => 0,
                'track_inventory' => true,
                'supplier_id' => $suppliers['SUP001']->id,
                'notes' => '停售原因：產品線更新',
                'status' => 'INACTIVE',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
