<?php

namespace Database\Seeders;

use App\Models\Supplier;
use Illuminate\Database\Seeder;

/**
 * 供應商資料 Seeder
 */
class SupplierSeeder extends Seeder
{
    public function run(): void
    {
        $suppliers = [
            [
                'code' => 'SUP001',
                'name' => '聯強國際股份有限公司',
                'short_name' => '聯強',
                'tax_id' => '23456789',
                'contact_person' => '陳建志',
                'phone' => '02-2506-1234',
                'fax' => '02-2506-1235',
                'email' => 'contact@synnex.com.tw',
                'address' => '台北市中山區民生東路三段128號',
                'website' => 'https://www.synnex.com.tw',
                'payment_terms' => 'NET30',
                'currency' => 'TWD',
                'tax_type' => 'TAX',
                'min_order_amount' => 10000.00,
                'shipping_method' => 'BY_AMOUNT',
                'free_shipping_threshold' => 50000.00,
                'bank_name' => '台北富邦銀行',
                'bank_code' => '012',
                'bank_branch' => '民生分行',
                'account_name' => '聯強國際股份有限公司',
                'account_number' => '123456789012',
                'notes' => '3C電子產品主要供應商',
                'status' => 'ACTIVE',
            ],
            [
                'code' => 'SUP002',
                'name' => '精技電腦股份有限公司',
                'short_name' => '精技',
                'tax_id' => '34567890',
                'contact_person' => '林志明',
                'phone' => '02-2795-6789',
                'fax' => '02-2795-6780',
                'email' => 'sales@unitech.com.tw',
                'address' => '台北市內湖區瑞光路513巷35號',
                'website' => 'https://www.unitech.com.tw',
                'payment_terms' => 'NET30',
                'currency' => 'TWD',
                'tax_type' => 'TAX',
                'min_order_amount' => 5000.00,
                'shipping_method' => 'FIXED',
                'free_shipping_threshold' => 30000.00,
                'bank_name' => '國泰世華銀行',
                'bank_code' => '013',
                'bank_branch' => '內湖分行',
                'account_name' => '精技電腦股份有限公司',
                'account_number' => '234567890123',
                'notes' => '電腦週邊設備供應商',
                'status' => 'ACTIVE',
            ],
            [
                'code' => 'SUP003',
                'name' => '統一生活事業股份有限公司',
                'short_name' => '統一生活',
                'tax_id' => '45678901',
                'contact_person' => '黃美玲',
                'phone' => '06-253-1234',
                'fax' => '06-253-1235',
                'email' => 'contact@pcsc.com.tw',
                'address' => '台南市永康區中正路301號',
                'website' => 'https://www.pxmart.com.tw',
                'payment_terms' => 'NET60',
                'currency' => 'TWD',
                'tax_type' => 'TAX',
                'min_order_amount' => 3000.00,
                'shipping_method' => 'BY_WEIGHT',
                'free_shipping_threshold' => 20000.00,
                'bank_name' => '第一銀行',
                'bank_code' => '007',
                'bank_branch' => '永康分行',
                'account_name' => '統一生活事業股份有限公司',
                'account_number' => '345678901234',
                'notes' => '食品飲料供應商',
                'status' => 'ACTIVE',
            ],
            [
                'code' => 'SUP004',
                'name' => '萊雅台灣股份有限公司',
                'short_name' => '萊雅',
                'tax_id' => '56789012',
                'contact_person' => '張雅惠',
                'phone' => '02-2175-8888',
                'fax' => '02-2175-8889',
                'email' => 'tw-contact@loreal.com',
                'address' => '台北市信義區松仁路100號',
                'website' => 'https://www.loreal.com.tw',
                'payment_terms' => 'NET30',
                'currency' => 'TWD',
                'tax_type' => 'TAX',
                'min_order_amount' => 8000.00,
                'shipping_method' => 'BY_AMOUNT',
                'free_shipping_threshold' => 25000.00,
                'bank_name' => '匯豐銀行',
                'bank_code' => '081',
                'bank_branch' => '台北分行',
                'account_name' => '萊雅台灣股份有限公司',
                'account_number' => '456789012345',
                'notes' => '美妝保養品供應商',
                'status' => 'ACTIVE',
            ],
            [
                'code' => 'SUP005',
                'name' => '台灣寢具實業有限公司',
                'short_name' => '台寢',
                'tax_id' => '67890123',
                'contact_person' => '吳建國',
                'phone' => '04-2358-7890',
                'fax' => '04-2358-7891',
                'email' => 'info@twbedding.com.tw',
                'address' => '台中市西屯區工業區一路50號',
                'website' => 'https://www.twbedding.com.tw',
                'payment_terms' => 'NET30',
                'currency' => 'TWD',
                'tax_type' => 'TAX',
                'min_order_amount' => 15000.00,
                'shipping_method' => 'FIXED',
                'free_shipping_threshold' => 50000.00,
                'bank_name' => '台中商業銀行',
                'bank_code' => '053',
                'bank_branch' => '西屯分行',
                'account_name' => '台灣寢具實業有限公司',
                'account_number' => '567890123456',
                'notes' => '居家寢具用品供應商',
                'status' => 'ACTIVE',
            ],
            [
                'code' => 'SUP006',
                'name' => '大千服飾國際有限公司',
                'short_name' => '大千服飾',
                'tax_id' => '78901234',
                'contact_person' => '周雅琪',
                'phone' => '02-2721-5678',
                'fax' => '02-2721-5679',
                'email' => 'contact@bigfashion.com.tw',
                'address' => '台北市大安區忠孝東路四段200號',
                'website' => 'https://www.bigfashion.com.tw',
                'payment_terms' => 'NET30',
                'currency' => 'TWD',
                'tax_type' => 'TAX',
                'min_order_amount' => 20000.00,
                'shipping_method' => 'BY_AMOUNT',
                'free_shipping_threshold' => 80000.00,
                'bank_name' => '玉山銀行',
                'bank_code' => '808',
                'bank_branch' => '忠孝分行',
                'account_name' => '大千服飾國際有限公司',
                'account_number' => '678901234567',
                'notes' => '服飾配件供應商',
                'status' => 'ACTIVE',
            ],
            // 停用供應商
            [
                'code' => 'SUP007',
                'name' => '舊時代電子有限公司',
                'short_name' => '舊時代',
                'tax_id' => '89012345',
                'contact_person' => '王志強',
                'phone' => '02-2888-9999',
                'email' => 'old@oldtech.com.tw',
                'address' => '台北市南港區南港路一段100號',
                'payment_terms' => 'NET30',
                'currency' => 'TWD',
                'tax_type' => 'TAX',
                'min_order_amount' => 5000.00,
                'notes' => '已停止合作',
                'status' => 'INACTIVE',
            ],
        ];

        foreach ($suppliers as $supplier) {
            Supplier::create($supplier);
        }
    }
}
